version: "3.8"
services:
  web-app:
    container_name: web-app
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./web-app:/usr/src/app
      - /usr/src/app/node_modules
 
  flask-app:
    restart: always
    container_name: flask-app
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
